### ISSUE TITLE
Adding required readme.txt

### ISSUE THREAD

**Issue by szepeviktor** [nk-o/lazy-blocks#144]
Hello!

This plugin lacks readme.txt.
https://plugins.trac.wordpress.org/browser/lazy-blocks/tags/2.0.7

What do you think about it?

**Comment by szepeviktor** [comment]
Somehow src/readme.md work!

Even in https://wordpress.org/plugins/developers/readme-validator/

How could it be??

**Comment by nk-o** [comment]
Hey.

Actually, I don’t remember why we use this version of the readme, but it was in our plugins since the first one released 3 years ago :)

What I know, that WordPress uses markdown parser + their own modifications to this parser, that's why our readme working with no problem.

Magic, nothing special 🧙‍♂️

**Comment by szepeviktor** [comment]
Thank you for your response.
