### ISSUE TITLE
Wierd behaviour for plus symbol

### ISSUE THREAD

**Issue by IamNivelir** [nk-o/lazy-blocks#59]
Hi.

I have spotted some bug, I think.
When I try to output some text with + symbol (in Text or Textarea type input) it's rendered like an empty space.

And html code is ignored, thus rendering just as code.
Please check if this issue is truly a bug.

**Comment by nk-o** [comment]
Hi.

Not sure I can repeat the bug with + symbols.

If you want to output text as HTML, use these brackets: `{{{my_control}}}`.

Block:

![image](https://user-images.githubusercontent.com/14810891/54812578-74d16580-4c9c-11e9-8240-f8de5a7a2534.png)

Code:

![image](https://user-images.githubusercontent.com/14810891/54812607-8adf2600-4c9c-11e9-94e8-6ed2b8767bf0.png)

**Comment by dabasti** [comment]
@nk-o I encountered a similar bug. I used the frontend Callback to output the HTML. Like IamNivelir said the plus is rendered as an empty space. I had to use `&plus;` as a workaround.

**Comment by friendrix** [comment]
The same issue but only for fields inside repeater. I found out that repeater data stored in single urlencoded string. So after urldecode all plusses dissappear.
To fix this I have changed I have changed urldecode to rawurldecode: in file **wp-content\plugins\lazy-blocks\classes\class-blocks.php** in function **render_callback** line 1030, instead of  `$attributes[ $k ] = json_decode( urldecode( $attr ), true );` place `$attributes[ $k ] = json_decode( rawurldecode( $attr ), true );`.
Now it work properly.

**Comment by nk-o** [comment]
So, guys @IamNivelir @dabasti, in your case this is not working without Repeater also? Or you have this problem only with Repeater?

**Comment by matt3224** [comment]
Hey @nk-o i just ran into this in repeater fields,

**Comment by matt3224** [comment]
Had to use `&plus;`
